import { DatabaseSchema, OptimizationReport } from "../types";
import { jsPDF } from "jspdf";
import { toPng } from "html-to-image";

export function generateDbml(schema: DatabaseSchema): string {
  let dbml = `// Generated by RelateX Studio\n// Dialect: ${schema.dialect}\n\n`;

  for (const table of schema.tables) {
    dbml += `Table ${table.name} {\n`;
    for (const col of table.columns) {
      const tags: string[] = [];
      if (col.isPrimaryKey) tags.push("pk");
      if (col.isUnique && !col.isPrimaryKey) tags.push("unique");
      if (!col.isNullable && !col.isPrimaryKey) tags.push("not null");
      if (col.defaultValue) tags.push(`default: \`${col.defaultValue}\``);

      const tagStr = tags.length ? ` [${tags.join(", ")}]` : "";
      dbml += `  ${col.name} ${col.type.toLowerCase()}${tagStr}\n`;
    }

    if (table.indexes && table.indexes.length > 0) {
      dbml += `\n  Indexes {\n`;
      for (const idx of table.indexes) {
        const u = idx.isUnique ? " [unique]" : "";
        dbml += `    (${idx.columns.join(", ")})${u}\n`;
      }
      dbml += `  }\n`;
    }
    dbml += `}\n\n`;
  }

  // Relations in DBML
  for (const rel of schema.relations) {
    const symbol = rel.cardinality === "1:1" ? "-" : "<";
    dbml += `Ref: ${rel.sourceTable}.${rel.sourceColumn} > ${rel.targetTable}.${rel.targetColumn}\n`;
  }

  return dbml;
}

export function generateMermaid(schema: DatabaseSchema): string {
  let mermaid = "erDiagram\n";

  for (const rel of schema.relations) {
    const cardSymbol =
      rel.cardinality === "1:1"
        ? "||--||"
        : rel.cardinality === "N:M"
        ? "}o--o{"
        : "}o--||";

    const sTable = rel.sourceTable.toUpperCase();
    const tTable = rel.targetTable.toUpperCase();
    mermaid += `    ${sTable} ${cardSymbol} ${tTable} : "${rel.sourceColumn} -> ${rel.targetColumn}"\n`;
  }

  for (const table of schema.tables) {
    const tName = table.name.toUpperCase();
    mermaid += `    ${tName} {\n`;
    for (const col of table.columns) {
      const typeClean = col.type.replace(/[^a-zA-Z0-9_]/g, "_");
      let keyTag = "";
      if (col.isPrimaryKey) keyTag = "PK";
      else if (col.isForeignKey) keyTag = "FK";
      mermaid += `        ${typeClean} ${col.name} ${keyTag}\n`;
    }
    mermaid += `    }\n`;
  }

  return mermaid;
}

export function downloadFile(filename: string, content: string, contentType = "text/plain") {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Export Schema & ERD to PDF Report
export async function exportSchemaToPdf(
  schema: DatabaseSchema,
  report?: OptimizationReport | null
): Promise<void> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  let y = margin;

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 28, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(56, 189, 248); // sky-400
  doc.text("RelateX Studio — Database Architecture & ERD Report", margin, 12);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text(
    `Dialect: ${schema.dialect}  •  Tables: ${schema.tables.length}  •  Relationships: ${schema.relations.length}  •  Generated: ${new Date().toLocaleDateString()}`,
    margin,
    20
  );

  y = 35;

  // Capture Canvas ERD snapshot if available
  const canvasElement = document.getElementById("canvas-stage");
  if (canvasElement) {
    try {
      const imgData = await toPng(canvasElement, {
        backgroundColor: "#020617",
        quality: 0.9,
        pixelRatio: 1.5,
      });

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(30, 41, 59);
      doc.text("1. Entity-Relationship Diagram Snapshot", margin, y);
      y += 6;

      const imgWidth = pageWidth - margin * 2;
      const imgHeight = 90;

      doc.addImage(imgData, "PNG", margin, y, imgWidth, imgHeight);
      y += imgHeight + 8;
    } catch (err) {
      console.warn("Could not capture canvas for PDF:", err);
    }
  }

  // Schema Overview Stats
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text("2. Schema Architecture Summary", margin, y);
  y += 6;

  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 24, 2, 2, "FD");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  doc.text(`Total Entities: ${schema.tables.length}`, margin + 5, y + 7);
  doc.text(`Relational Foreign Keys: ${schema.relations.length}`, margin + 55, y + 7);
  doc.text(`Source Dialect: ${schema.dialect}`, margin + 120, y + 7);

  if (report) {
    doc.text(`Health Audit Score: ${report.healthScore}/100`, margin + 5, y + 15);
    doc.text(`Normalization Score: ${report.normalizationScore}/100`, margin + 55, y + 15);
    doc.text(`Estimated Speedup: ${report.estimatedQuerySpeedup}`, margin + 120, y + 15);
  } else {
    doc.text(`Optimization Status: Analyzed & Validated in RelateX`, margin + 5, y + 15);
  }

  y += 32;

  // New Page: Data Dictionary (Table Entities)
  doc.addPage();
  y = margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("3. Data Dictionary & Entity Definitions", margin, y);
  y += 8;

  for (const table of schema.tables) {
    // Check if space remains on page
    if (y > pageHeight - 45) {
      doc.addPage();
      y = margin;
    }

    doc.setFillColor(241, 245, 249);
    doc.setDrawColor(203, 213, 225);
    doc.rect(margin, y, pageWidth - margin * 2, 7, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(`TABLE: ${table.name}`, margin + 3, y + 5);

    if (table.category) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(`Category: ${table.category}`, pageWidth - margin - 35, y + 5);
    }

    y += 9;

    // Table Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text("Column Name", margin + 3, y);
    doc.text("Data Type", margin + 50, y);
    doc.text("Key Attributes", margin + 95, y);
    doc.text("Nullable", margin + 140, y);
    y += 4;
    doc.line(margin, y - 1, pageWidth - margin, y - 1);

    // Columns
    doc.setFont("helvetica", "normal");
    for (const col of table.columns) {
      if (y > pageHeight - 15) {
        doc.addPage();
        y = margin;
      }

      doc.setFontSize(8);
      doc.setTextColor(30, 41, 59);
      doc.text(col.name, margin + 3, y);
      doc.text(col.type, margin + 50, y);

      let keyAttr = "-";
      if (col.isPrimaryKey) keyAttr = "PRIMARY KEY [PK]";
      else if (col.isForeignKey) keyAttr = `FOREIGN KEY [FK] -> ${col.foreignKeyRef?.table || ""}`;
      else if (col.isUnique) keyAttr = "UNIQUE";

      doc.setTextColor(col.isPrimaryKey ? 14 : col.isForeignKey ? 79 : 71, col.isPrimaryKey ? 165 : col.isForeignKey ? 70 : 85, col.isPrimaryKey ? 233 : col.isForeignKey ? 229 : 105);
      doc.text(keyAttr, margin + 95, y);

      doc.setTextColor(col.isNullable ? 100 : 220, col.isNullable ? 116 : 38, col.isNullable ? 139 : 38);
      doc.text(col.isNullable ? "YES" : "NOT NULL", margin + 140, y);

      y += 4.5;
    }

    y += 4;
  }

  // Relations summary page if relations exist
  if (schema.relations.length > 0) {
    if (y > pageHeight - 60) {
      doc.addPage();
      y = margin;
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text("4. Relational Foreign Key Map", margin, y);
    y += 6;

    for (const rel of schema.relations) {
      if (y > pageHeight - 15) {
        doc.addPage();
        y = margin;
      }

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(51, 65, 85);
      doc.text(
        `• ${rel.sourceTable}.${rel.sourceColumn}  -->  ${rel.targetTable}.${rel.targetColumn}  (${rel.cardinality})`,
        margin + 4,
        y
      );
      y += 5;
    }
  }

  // Performance Recommendations if report is available
  if (report && (report.missingIndexes?.length > 0 || report.compositeIndexes?.length > 0)) {
    doc.addPage();
    y = margin;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.text("5. AI Performance & Index Optimization Strategies", margin, y);
    y += 8;

    if (report.missingIndexes?.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(180, 83, 9); // amber-700
      doc.text("Recommended Missing Covering Indexes:", margin, y);
      y += 6;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(30, 41, 59);

      for (const idxItem of report.missingIndexes) {
        if (y > pageHeight - 20) {
          doc.addPage();
          y = margin;
        }

        doc.text(`• [${idxItem.severity}] ${idxItem.table} (${idxItem.columns.join(", ")})`, margin + 4, y);
        y += 4;
        doc.setTextColor(100, 116, 139);
        doc.text(`   SQL: ${idxItem.sql}`, margin + 4, y);
        doc.setTextColor(30, 41, 59);
        y += 5;
      }
    }
  }

  // Add Page Numbers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`RelateX Studio • Page ${i} of ${totalPages}`, pageWidth - margin - 35, pageHeight - 7);
  }

  doc.save(`relatex_schema_report_${Date.now()}.pdf`);
}
